version: "3"
services:
  connector-vti:
    build: .
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=VTI"
      - CONNECTOR_SCOPE=malware,indicator,sighting
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - "CONNECTOR_ENTITY_NAME=VirusTotal Intelligence"
      - "CONNECTOR_ENTITY_DESCRIPTION=VTI Enterprise connector"

    restart: always
